#!/bin/bash

## @brief Параметры настройки проекта

CONFIG_PROJECT_INSTANCE="HomeVpn"

CONFIG_OPENVPN_SERVER_PORT=35000
CONFIG_OPENVPN_DATA_DIR_PATH="${GLOBAL_CONFIG_OPT_DIR_PATH}/${CONFIG_PROJECT_INSTANCE}"
CONFIG_OPENVPN_SERVER_DATA_DIR_PATH="${CONFIG_OPENVPN_DATA_DIR_PATH}/server"
CONFIG_OPENVPN_SERVER_LOG_DIR_PATH="${CONFIG_OPENVPN_SERVER_DATA_DIR_PATH}/logs"
CONFIG_OPENVPN_SERVER_CONFIG_FILE_PATH="${CONFIG_OPENVPN_SERVER_DATA_DIR_PATH}/server.ovpn"
CONFIG_EASYRSA_PKI_DIR_PATH="${CONFIG_OPENVPN_SERVER_DATA_DIR_PATH}/pki"

CONFIG_OPENVPN_CLIENT_DATA_DIR_PATH_TEMPLATE="${CONFIG_OPENVPN_DATA_DIR_PATH}/client/%s"
CONFIG_OPENVPN_CLIENT_LOG_DIR_PATH_TEMPLATE="${OPENVPN_CLIENT_DATA_DIR_PATH}/logs"
CONFIG_OPENVPN_CLIENT_CONFIG_FILE_PATH_TEMPLATE="${OPENVPN_CLIENT_DATA_DIR_PATH}/client.ovpn"

CONFIG_MY_CURRENT_IP_ADDRESS_AND_PORT_FILE_PATH="${CONFIG_OPENVPN_SERVER_DATA_DIR_PATH}/my_current_ip_address_and_port.txt"

CONFIG_NETWORK_BRIDGE_IP_ADDRESS_AND_MASK="172.20.0.5/16"
CONFIG_NETWORK_BRIDGE_DATA_DIR_PATH="${CONFIG_OPENVPN_SERVER_DATA_DIR_PATH}/network_bridge"

CONFIG_DNS_DHCP_DATA_DIR_PATH="${CONFIG_NETWORK_BRIDGE_DATA_DIR_PATH}/dns_dhcp"
CONFIG_DNS_SUFFIX="homevpn.org"
CONFIG_DNS_MY_HOST="myhost.${CONFIG_DNS_SUFFIX}"

CONFIG_VM_REGISTRY_DIR_PATH="${HOME_VPN_PROJECT_ROOT}/vm"
CONFIG_VIRTIO_WIN_DRIVERS_URL="https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/stable-virtio/virtio-win.iso"

CONFIG_INTERNET_NETWORK_INTERFACE=""
CONFIG_LOCAL_NETWORK_INTERFACE=""