
WIN_SHELL_SCRIPT_FILE_EXTENSION_DEFAULT = ".cmd"
UNIX_SHELL_SCRIPT_FILE_EXTENSION_DEFAULT = ".sh"

WIN_SHELL_SCRIPT_FILE_EXTENSION_LIST = {WIN_SHELL_SCRIPT_FILE_EXTENSION_DEFAULT, ".bat", ".com"}
UNIX_SHELL_SCRIPT_FILE_EXTENSION_LIST = {UNIX_SHELL_SCRIPT_FILE_EXTENSION_DEFAULT, ".bash"}
